version: '3'

services:
  registry:
    build:
      context: .
    container_name: registry
    environment:
      - REGISTRY=true
  member1:
    build:
      context: .
    container_name: member1
    environment:
      - "REGISTRY_ADDR=registry:90"
      - APP=TRUE
      - VERBOSE=ON
      - NUM_THREADS=2
      - DELAY=2
    ports:
      - "8080:80"

  member2:
    build:
      context: .
    container_name: member2
    environment:
      - "REGISTRY_ADDR=registry:90"
      - APP=TRUE
      - VERBOSE=ON
      - NUM_THREADS=2
      - DELAY=1
    ports:
      - "8081:80"

  member3:
    build:
      context: .
    container_name: member3
    environment:
      - "REGISTRY_ADDR=registry:90"
      - APP=TRUE
      - VERBOSE=ON
      - NUM_THREADS=2
      - DELAY=2
    ports:
      - "8082:80"
