version: '3'

services:
  registry:
    build:
      context: .
    container_name: registry
    environment:
      - REGISTRY=true
    ports:
      - '90'


  member1:
    build:
      context: .
    container_name: member1
    environment:
      - APP=true
      - REGISTRY_ADDR=registry:90
      - NUM_THREADS=2
      - DELAY=1
      - VERBOSE=true
      - ID=0
    ports:
      - 8080:80

  member2:
    build:
      context: .
    container_name: member2
    environment:
      - APP=true
      - REGISTRY_ADDR=registry:90
      - NUM_THREADS=2
      - DELAY=1
      - VERBOSE=true
      - ID=1
    ports:
      - 8081:80

  member3:
    build:
      context: .
    container_name: member3
    environment:
      - APP=true
      - REGISTRY_ADDR=registry:90
      - NUM_THREADS=2
      - DELAY=1
      - VERBOSE=true
      - ID=2
    ports:
      - 8082:80

  member4:
    build:
      context: .
    container_name: member4
    environment:
      - APP=true
      - REGISTRY_ADDR=registry:90
      - NUM_THREADS=2
      - DELAY=1
      - VERBOSE=true
      - ID=3
    ports:
      - 8083:80
