// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EndToEndServiceClient is the client API for EndToEndService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EndToEndServiceClient interface {
	SendMessage(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ResponseMessage, error)
}

type endToEndServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEndToEndServiceClient(cc grpc.ClientConnInterface) EndToEndServiceClient {
	return &endToEndServiceClient{cc}
}

func (c *endToEndServiceClient) SendMessage(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, "/EndToEndService/sendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndToEndServiceServer is the server API for EndToEndService service.
// All implementations must embed UnimplementedEndToEndServiceServer
// for forward compatibility
type EndToEndServiceServer interface {
	SendMessage(context.Context, *RequestMessage) (*ResponseMessage, error)
	mustEmbedUnimplementedEndToEndServiceServer()
}

// UnimplementedEndToEndServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEndToEndServiceServer struct {
}

func (UnimplementedEndToEndServiceServer) SendMessage(context.Context, *RequestMessage) (*ResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedEndToEndServiceServer) mustEmbedUnimplementedEndToEndServiceServer() {}

// UnsafeEndToEndServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EndToEndServiceServer will
// result in compilation errors.
type UnsafeEndToEndServiceServer interface {
	mustEmbedUnimplementedEndToEndServiceServer()
}

func RegisterEndToEndServiceServer(s grpc.ServiceRegistrar, srv EndToEndServiceServer) {
	s.RegisterService(&EndToEndService_ServiceDesc, srv)
}

func _EndToEndService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndToEndServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EndToEndService/sendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndToEndServiceServer).SendMessage(ctx, req.(*RequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// EndToEndService_ServiceDesc is the grpc.ServiceDesc for EndToEndService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EndToEndService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EndToEndService",
	HandlerType: (*EndToEndServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendMessage",
			Handler:    _EndToEndService_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
