definitions:
  multicastapp.Member:
    properties:
      address:
        type: string
      member_id:
        type: string
      ready:
        type: boolean
    type: object
  multicastapp.Message:
    properties:
      MessageHeader:
        additionalProperties:
          type: string
        type: object
      Payload:
        items:
          type: integer
        type: array
    type: object
  multicastapp.MulticastInfo:
    properties:
      members:
        additionalProperties:
          $ref: '#/definitions/multicastapp.Member'
        type: object
      multicast_id:
        type: string
      multicast_type:
        type: string
      received_messages:
        type: integer
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: salvatimartina97@gmail.com
  description: This is a multicast API
  title: MULTICAST API
  version: "1.0"
paths:
  /deliver/:mId:
    get:
      consumes:
      - application/json
      description: Get Deliver-Message of Group by id
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/multicastapp.Message'
            type: array
      summary: Get Deliver-Message queue
      tags:
      - groups
  /groups:
    get:
      consumes:
      - application/json
      description: Get Multicast Group
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/multicastapp.MulticastInfo'
      summary: Get Multicast Group
      tags:
      - groups
    post:
      consumes:
      - application/json
      description: Create Multicast Group
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/multicastapp.MulticastInfo'
      summary: Create Multicast Group
      tags:
      - groups
  /groups/:mId:
    get:
      consumes:
      - application/json
      description: Get Multicast Group by id
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/multicastapp.MulticastInfo'
      summary: Get Multicast Group by id
      tags:
      - groups
    put:
      consumes:
      - application/json
      description: Start multicast by id
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/multicastapp.MulticastInfo'
      summary: Start multicast by id
      tags:
      - groups
  /messaging/:mId:
    get:
      consumes:
      - application/json
      description: Get Message of Group by id
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/multicastapp.Message'
            type: array
      summary: Get Message of Group by id
      tags:
      - groups
    post:
      consumes:
      - application/json
      description: Multicast a message to a group G
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/multicastapp.Message'
      summary: Multicast a message to a group G
      tags:
      - messaging
swagger: "2.0"
