basePath: /docs
definitions:
  main.Member:
    properties:
      address:
        type: string
      member_id:
        type: string
      ready:
        type: boolean
    type: object
  main.Message:
    properties:
      MessageHeader:
        additionalProperties:
          type: string
        type: object
      Payload:
        items:
          type: integer
        type: array
    type: object
  main.MulticastGroup:
    properties:
      client_id:
        type: string
      group:
        $ref: '#/definitions/main.MulticastInfo'
      messages:
        items:
          $ref: '#/definitions/main.Message'
        type: array
    type: object
  main.MulticastInfo:
    properties:
      members:
        additionalProperties:
          $ref: '#/definitions/main.Member'
        type: object
      multicast_id:
        type: string
      multicast_type:
        type: string
      received_messages:
        type: integer
      status:
        type: string
    type: object
host: localhost
info:
  contact:
    email: salvatimartina97@gmail.com
  description: This is a sample service for managing groups multicast
  title: Orders API
  version: "1.0"
paths:
  /groups:
    get:
      consumes:
      - application/json
      description: Get details of all groups
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.MulticastGroup'
      summary: Get details of all groups
      tags:
      - groups
    post:
      consumes:
      - application/json
      description: Create a group from an id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.MulticastGroup'
      summary: Create a group from an id
      tags:
      - groups
swagger: "2.0"
